language: generic

install:
  - ./scripts/ci-install.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
env:
  - TEST_SUITE=static
  - TEST_SUITE=unit
script:
  - if [[ $TEST_SUITE == "static" ]]; then source activate test && ./scripts/check.sh; fi
  - if [[ $TEST_SUITE == "static" ]]; then source activate test && ./scripts/build-doc.sh; fi
  - if [[ $TEST_SUITE == "unit" ]]; then source activate test && pytest tests --cov=./ --cov-report term-missing; fi
after_success:
  - if [[ $TEST_SUITE == "unit" ]]; then codecov; fi
