language: python

install:
  - ./scripts/ci-install.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
env:
  - TEST_SUITE=static
  - TEST_SUITE=unit
script:
  - if [[ $TEST_SUITE == "static" ]]; then source activate test && flake8 && pydocstyle myia && isort -c -df && black --check .; fi
  - if [[ $TEST_SUITE == "static" ]]; then source activate test && cd docs && sphinx-apidoc -fo source/ ../myia/ && sphinx-build -W -b html . _build; fi
  - if [[ $TEST_SUITE == "unit" ]]; then source activate test && pytest tests --cov=./ --cov-report term-missing; fi
after_success:
  - if [[ $TEST_SUITE == "unit" ]]; then codecov; fi
