[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "myia"
version = "0.0.0"
description = "A linear algebra compiler for a subset of Python"
authors = ["Mila development team"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/mila-iqia/myia"

[tool.poetry.dependencies]
python = ">=3.7,<3.8a0"
antlr4-python3-runtime = "4.7.2"
asttokens = "^2.0.3"
colorama = "^0.4.3"
gym = "^0.17.1"
numpy = "^1.18.2"
opt_einsum = "^3.2.0"
pillow = "<7"
prettyprinter = "^0.18.0"
"ruamel.yaml" = "^0.16.10"
"ruamel.yaml.clib" = "^0.2.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
docopt = "^0.6.2"
flake8 = "^3.7.9"
isort = "^4.3.21"
pydocstyle = "5.0.1"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
sphinx = "^2.4.4"

[custom.tool.conda.dependencies]
"abergeron::tvm" = "0.7dev1+0.*"
"pytorch::pytorch" = "1.3.0"
"pytorch::torchvision" = "0.4.1"

[custom.tool.conda.cpu-dependencies]
"pytorch::cpuonly" = "1.0"

[custom.tool.conda.gpu-dependencies]
cudatoolkit = "10.1"
cudnn = "6.0"

[tool.black]
line-length = 80

[tool.isort]
known_first_party = "myia,debug"
known_third_party = "torch,torchvision,tvm,hrepr,buche,breakword,docopt,gym"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.coverage.run]
omit = [
    "conftest.py",
    "setup.py",
    "tests/*",
    "debug/*",
    "myia/debug/*",
    "examples/*",
]

[tool.coverage.report]
exclude_lines = [
    "@pyoverload",
    "@abstractmethod",
    "@compile",
    "@core",
    "@wrap_grad_transform",
    "@bprop_to_grad_transform",
    "pragma: no cover",
    "AssertionError",
    "NotImplementedError",
    "untested_legacy",
]
