[tool.black]
line-length = 80

[tool.isort]
known_first_party = "myia,debug"
known_third_party = "torch,tvm,hrepr,buche,breakword,docopt"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
