[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "myia"
version = "0.0.0"
description = "A linear algebra compiler for a subset of Python"
authors = ["Mila development team"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/mila-iqia/myia"

[tool.poetry.dependencies]
python = ">=3.7,<3.8a0"

[tool.poetry.dev-dependencies]

[tool.black]
line-length = 80

[tool.isort]
known_first_party = "myia,debug"
known_third_party = "torch,torchvision,tvm,hrepr,buche,breakword,docopt,gym"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.coverage.run]
omit = [
    "conftest.py",
    "setup.py",
    "tests/*",
    "debug/*",
    "myia/debug/*",
    "examples/*",
]

[tool.coverage.report]
exclude_lines = [
    "@pyoverload",
    "@abstractmethod",
    "@compile",
    "@core",
    "@wrap_grad_transform",
    "@bprop_to_grad_transform",
    "pragma: no cover",
    "AssertionError",
    "NotImplementedError",
    "untested_legacy",
]
